version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27018:27017"
    networks:
      - default
  
  transaction:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - default